#pragma once

#include <QDate>
#include <QDateTime>
#include <QList>
#include <QString>
#include <QStringList>
#include <QTime>
#include <QtGlobal>
#include <optional>

enum class TaskPriority {
    Low = 0,
    Medium = 1,
    High = 2
};

struct TodoItem {
    struct FocusRecord {
        QDateTime completedAt;
        int focusMinutes = 0;
    };

    QString id;
    QString title;
    QDate date;
    TaskPriority priority = TaskPriority::Medium;
    QDateTime dueAt;
    QStringList tags;
    bool completed = false;
    QDateTime completedAt;
    qint64 trackedSeconds = 0;
    QDateTime timingStartedAt;
    QList<FocusRecord> focusRecords;
    QString sourcePlanId;
    bool autoGeneratedFromPlan = false;
};

struct TodoPlan {
    QString id;
    QString title;
    QDate startDate;
    QDate endDate;
    TaskPriority priority = TaskPriority::Medium;
    QTime dueTime;
    QStringList tags;
    bool paused = false;
    QDate lastGeneratedDate;
};

struct TodoStats {
    int totalToday = 0;
    int completedToday = 0;
    int focusToday = 0;
    int focusLast7Days = 0;
    qint64 trackedSecondsToday = 0;
    qint64 trackedSecondsAll = 0;
};

class TaskStorage {
public:
    TaskStorage();

    bool load();
    bool save() const;
    QString storageFilePath() const;
    bool setStorageFilePath(const QString &filePath);

    QList<TodoItem> allTodos() const;
    QList<TodoPlan> allPlans() const;
    QStringList availableTags() const;
    QList<TodoItem> todosForDate(const QDate &date) const;
    std::optional<TodoItem> todoById(const QString &id) const;
    std::optional<TodoPlan> planById(const QString &id) const;
    bool addTodo(const QString &title,
                 const QDate &date,
                 TaskPriority priority,
                 const QDateTime &dueAt,
                 const QStringList &tags);
    bool addDailyPlan(const QString &title,
                      const QDate &startDate,
                      const QDate &endDate,
                      TaskPriority priority,
                      const QDateTime &dueAtTemplate,
                      const QStringList &tags,
                      int *generatedCount = nullptr);
    bool updatePlan(const TodoPlan &plan, bool syncPastUnfinished = false);
    bool addDailyTodoPlan(const QString &title,
                          const QDate &startDate,
                          const QDate &endDate,
                          TaskPriority priority,
                          const QDateTime &dueAtTemplate,
                          const QStringList &tags,
                          int *createdCount = nullptr);
    bool setPlanPaused(const QString &planId, bool paused);
    bool removePlan(const QString &planId);
    int ensureDailyPlansGenerated(const QDate &untilDate);
    bool updateTodo(const TodoItem &todo);
    bool removeTodo(const QString &id);
    bool removeTag(const QString &tag);
    bool setTodoCompleted(const QString &id, bool completed);
    bool startTodoTiming(const QString &id);
    bool stopTodoTiming(const QString &id);
    bool addTrackedSeconds(const QString &id, qint64 seconds);
    bool hasActiveTodoTiming() const;
    std::optional<TodoItem> activeTimedTodo() const;

    bool addFocusRecord(const QString &todoId, const QDateTime &completedAt, int focusMinutes);
    QList<TodoItem::FocusRecord> focusRecordsForDate(const QDate &date) const;
    int focusCountForDate(const QDate &date) const;
    int focusCountForRecentDays(const QDate &endDate, int days) const;

    TodoStats currentStats(const QDate &date) const;
    static qint64 effectiveTrackedSeconds(const TodoItem &todo, const QDateTime &referenceTime);

private:
    QString m_filePath;
    QList<TodoItem> m_todos;
    QList<TodoPlan> m_plans;
    QStringList m_tagCatalog;

    static QString generateId();
    bool ensureStorageDir() const;
    static QStringList normalizeTags(const QStringList &tags);
    static void finalizeTimingSession(TodoItem &todo, const QDateTime &endedAt);
    static QStringList builtInTags();
    bool generatePlanTodosUntil(TodoPlan &plan, const QDate &untilDate, int *generatedCount = nullptr);
    bool hasPlanTodoOnDate(const QString &planId, const QDate &date) const;
    void rebuildTagCatalog();
};
